### ISSUE TITLE
ensure that scripts and data are interpretable to others

### ISSUE THREAD

**Issue by teixeirak** [SCBI-ForestGEO/Coring-Mortality#2]
@RHelcoski, it would be helpful to make some minor changes in this repository to ensure that the files will be interpretable to others. For example:
- [x] rename files you inherited from Tori to be meaningful in the context of your paper
- [x] change setwd command so its not localized to your machine
- [x] create readme or metadata files as needed to ensure that everything is clearly explained.

**Comment by RHelcoski** [comment]
I believe this is now finished.

**Comment by teixeirak** [comment]
Thanks!
